---
title: "HW 6"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(mgcv)
library(modelr)

library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


# Problem 2 

```{r, echo = FALSE, warning = FALSE, message = FALSE}
homicide_rawdf = read_csv("./data/homicide-data.csv")
```
_Description of raw data_ This dataset overviews demographic and geographic data for homicide victims across various cities in the United States. It has `n rows(homicide_rawdf)` rows and `ncols(homicide_rawdf)` columns.

Steps: 

1. Cleaned the data

```{r, echo = FALSE}
homicide_cleandf = 
  homicide_rawdf %>% 
  mutate(
    city_state = str_c(city,", ", state), 
    solved = case_when(disposition == "Closed by arrest" ~ 1,
                          disposition != "Closed by arrest" ~ 0)
  ) %>% 
  filter(
    city_state != "Dallas, Tx", 
    city_state != "Phoenix, AZ",
    city_state != "Kansas City, MO", 
    city_state != "Tulsa, AL"
  ) %>% 
  filter(
    victim_race == "White" | victim_race == "Black"
  ) %>% 
  relocate(city_state)
```

2. Use the glm function for Baltimore 

```{r}

```




